name: personal_website
services:
    nfs_server:
        build:
            context: .
        stdin_open: true
        tty: true
        ports:
          - "1313:1313"   # maps host port to container port
        container_name: personal_website
        image: personal_website
        command: hugo server --bind 0.0.0.0 --baseURL http://localhost:1313 --port 1313
